// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekrsdslfrszqzlewljug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrcnNkc2xmcnN6cXpsZXdsanVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NDgyNDgsImV4cCI6MjA2NzUyNDI0OH0.eBAgCxDjRQgXiRKqi8I2jN9gn29LtF56hjtCW3_lYzE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});